[{'Q1': 'Eventos culturais',
  'Q2': 'Algumas vezes por semestre',
  'Q3': 'Outros: Site institucional',
  'Q4': ['Inscrição online',
   'Histórico de participação',
   'Recomendações personalizadas'],
  'Q5': 'Não gostaria de receber notificações',
  'Q6': 'Processo de inscrição',
  'Q7': 'Pouco importante',
  'Q8': 'Não vejo utilidade',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Insatisfeito(a)',
  'Q11': 'Ciências da Computação',
  'Q12': 'Não trabalho',
  'Q13': 'Menos de 2 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  ' ': ['Melhorar habilidades profissionais',
   'Relaxar e fazer algo divertido',
   'Conectar-se com outras pessoas']},
 {'Q1': 'Workshops',
  'Q2': 'Frequentemente (uma ou mais vezes por mês)',
  'Q3': 'E-mails da instituição',
  'Q4': ['Calendário integrado de eventos',
   'Notificações sobre mudanças nos eventos',
   'Recomendações personalizadas',
   'Inscrição online',
   'Rede de contatos entre participantes'],
  'Q5': 'Não gostaria de receber notificações',
  'Q6': 'Acessar certificados ou comprovantes de participação',
  'Q7': 'Pouco importante',
  'Q8': 'Não, mas gostaria de usar',
  'Q9': 'Melhor comunicação',
  'Q10': 'Muito insatisfeito(a)',
  'Q11': 'Ciências da Computação',
  'Q12': 'Sim, trabalho integral',
  'Q13': 'Entre 5 e 10 horas',
  'Q14': 'Moderada, utilizo quando necessário',
  'Q15': ['Conectar-se com outras pessoas',
   'Explorar novos interesses',
   'Outros: Aumentar networking']},
 {'Q1': 'Cursos de curta duração',
  'Q2': 'Algumas vezes por semestre',
  'Q3': 'Redes sociais',
  'Q4': ['Exploração de atividades por categoria',
   'Calendário integrado de eventos',
   'Notificações sobre mudanças nos eventos'],
  'Q5': 'Sim, por mensagem no celular',
  'Q6': 'Encontrar atividades relevantes',
  'Q7': 'Extremamente importante',
  'Q8': 'Não, mas gostaria de usar',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Satisfeito(a)',
  'Q11': 'Ciências da Computação',
  'Q12': 'Sim, estou em estágio',
  'Q13': 'Entre 5 e 10 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Melhorar habilidades profissionais',
   'Ganhar créditos acadêmicos',
   'Conectar-se com outras pessoas']},
 {'Q1': 'Eventos culturais',
  'Q2': 'Nunca',
  'Q3': 'E-mails da instituição',
  'Q4': ['Rede de contatos entre participantes',
   'Notificações sobre mudanças nos eventos',
   'Exploração de atividades por categoria'],
  'Q5': 'Sim, por e-mail',
  'Q6': 'Encontrar atividades relevantes',
  'Q7': 'Importante',
  'Q8': 'Não vejo utilidade',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Muito insatisfeito(a)',
  'Q11': 'Medicina',
  'Q12': 'Sim, trabalho integral',
  'Q13': 'Entre 5 e 10 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Outros: Aumentar networking',
   'Relaxar e fazer algo divertido',
   'Ganhar créditos acadêmicos']},
 {'Q1': 'Grupos de estudo',
  'Q2': 'Raramente',
  'Q3': 'Outros: Site institucional',
  'Q4': ['Calendário integrado de eventos',
   'Exploração de atividades por categoria',
   'Recomendações personalizadas',
   'Rede de contatos entre participantes'],
  'Q5': 'Não gostaria de receber notificações',
  'Q6': 'Acompanhar as datas dos eventos',
  'Q7': 'Moderadamente importante',
  'Q8': 'Não vejo utilidade',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Insatisfeito(a)',
  'Q11': 'Ciências da Computação',
  'Q12': 'Sim, estou em estágio',
  'Q13': 'Mais de 10 horas',
  'Q14': 'Muito alta, utilizo frequentemente',
  'Q15': ['Ganhar créditos acadêmicos', 'Melhorar habilidades profissionais']},
 {'Q1': 'Cursos de curta duração',
  'Q2': 'Raramente',
  'Q3': 'Comunicados internos',
  'Q4': ['Exploração de atividades por categoria',
   'Notificações sobre mudanças nos eventos',
   'Avaliações e feedbacks das atividades',
   'Inscrição online',
   'Calendário integrado de eventos'],
  'Q5': 'Sim, por e-mail',
  'Q6': 'Processo de inscrição',
  'Q7': 'Pouco importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Melhor comunicação',
  'Q10': 'Muito satisfeito(a)',
  'Q11': 'Engenharia de Computação',
  'Q12': 'Não, mas procuro trabalho',
  'Q13': 'Entre 5 e 10 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Ganhar créditos acadêmicos',
   'Explorar novos interesses',
   'Melhorar habilidades profissionais']},
 {'Q1': 'Outros: Voluntariado',
  'Q2': 'Raramente',
  'Q3': 'E-mails da instituição',
  'Q4': ['Rede de contatos entre participantes',
   'Avaliações e feedbacks das atividades',
   'Exploração de atividades por categoria',
   'Recomendações personalizadas'],
  'Q5': 'Sim, por e-mail',
  'Q6': 'Processo de inscrição',
  'Q7': 'Moderadamente importante',
  'Q8': 'Não, mas gostaria de usar',
  'Q9': 'Integração com calendário pessoal',
  'Q10': 'Satisfeito(a)',
  'Q11': 'Psicologia',
  'Q12': 'Sim, trabalho integral',
  'Q13': 'Mais de 10 horas',
  'Q14': 'Moderada, utilizo quando necessário',
  'Q15': ['Melhorar habilidades profissionais',
   'Relaxar e fazer algo divertido',
   'Outros: Aumentar networking']},
 {'Q1': 'Cursos de curta duração',
  'Q2': 'Algumas vezes por semestre',
  'Q3': 'Comunicados internos',
  'Q4': ['Rede de contatos entre participantes',
   'Calendário integrado de eventos',
   'Exploração de atividades por categoria',
   'Recomendações personalizadas'],
  'Q5': 'Sim, por ambos (e-mail e mensagem)',
  'Q6': 'Outros: Dificuldade de conciliar horários',
  'Q7': 'Extremamente importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Satisfeito(a)',
  'Q11': 'Direito',
  'Q12': 'Sim, trabalho integral',
  'Q13': 'Entre 2 e 5 horas',
  'Q14': 'Baixa, prefiro métodos manuais',
  'Q15': ['Conectar-se com outras pessoas', 'Relaxar e fazer algo divertido']},
 {'Q1': 'Workshops',
  'Q2': 'Frequentemente (uma ou mais vezes por mês)',
  'Q3': 'Outros: Site institucional',
  'Q4': ['Recomendações personalizadas',
   'Inscrição online',
   'Rede de contatos entre participantes',
   'Exploração de atividades por categoria'],
  'Q5': 'Sim, por mensagem no celular',
  'Q6': 'Acessar certificados ou comprovantes de participação',
  'Q7': 'Extremamente importante',
  'Q8': 'Sim, ocasionalmente',
  'Q9': 'Mais opções de atividades',
  'Q10': 'Muito insatisfeito(a)',
  'Q11': 'Engenharia Elétrica',
  'Q12': 'Sim, trabalho integral',
  'Q13': 'Menos de 2 horas',
  'Q14': 'Moderada, utilizo quando necessário',
  'Q15': ['Relaxar e fazer algo divertido', 'Conectar-se com outras pessoas']},
 {'Q1': 'Grupos de estudo',
  'Q2': 'Frequentemente (uma ou mais vezes por mês)',
  'Q3': 'E-mails da instituição',
  'Q4': ['Avaliações e feedbacks das atividades',
   'Calendário integrado de eventos',
   'Inscrição online',
   'Exploração de atividades por categoria'],
  'Q5': 'Sim, por mensagem no celular',
  'Q6': 'Encontrar atividades relevantes',
  'Q7': 'Moderadamente importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Facilidade de inscrição',
  'Q10': 'Muito insatisfeito(a)',
  'Q11': 'Nutrição',
  'Q12': 'Sim, estou em estágio',
  'Q13': 'Menos de 2 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Conectar-se com outras pessoas',
   'Relaxar e fazer algo divertido',
   'Melhorar habilidades profissionais']},
 {'Q1': 'Eventos esportivos',
  'Q2': 'Frequentemente (uma ou mais vezes por mês)',
  'Q3': 'Outros: Site institucional',
  'Q4': ['Avaliações e feedbacks das atividades',
   'Recomendações personalizadas',
   'Calendário integrado de eventos',
   'Rede de contatos entre participantes',
   'Inscrição online'],
  'Q5': 'Sim, por mensagem no celular',
  'Q6': 'Acompanhar as datas dos eventos',
  'Q7': 'Moderadamente importante',
  'Q8': 'Não vejo utilidade',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Muito satisfeito(a)',
  'Q11': 'Física',
  'Q12': 'Sim, trabalho parcial',
  'Q13': 'Menos de 2 horas',
  'Q14': 'Muito alta, utilizo frequentemente',
  'Q15': ['Outros: Aumentar networking', 'Conectar-se com outras pessoas']},
 {'Q1': 'Workshops',
  'Q2': 'Raramente',
  'Q3': 'Comunicados internos',
  'Q4': ['Histórico de participação',
   'Calendário integrado de eventos',
   'Notificações sobre mudanças nos eventos',
   'Recomendações personalizadas',
   'Exploração de atividades por categoria'],
  'Q5': 'Sim, por ambos (e-mail e mensagem)',
  'Q6': 'Outros: Dificuldade de conciliar horários',
  'Q7': 'Pouco importante',
  'Q8': 'Sim, ocasionalmente',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Satisfeito(a)',
  'Q11': 'Química Bacharelado',
  'Q12': 'Sim, estou em estágio',
  'Q13': 'Menos de 2 horas',
  'Q14': 'Muito alta, utilizo frequentemente',
  'Q15': ['Melhorar habilidades profissionais',
   'Explorar novos interesses',
   'Outros: Aumentar networking']},
 {'Q1': 'Cursos de curta duração',
  'Q2': 'Frequentemente (uma ou mais vezes por mês)',
  'Q3': 'Outros: Site institucional',
  'Q4': ['Avaliações e feedbacks das atividades',
   'Calendário integrado de eventos',
   'Inscrição online'],
  'Q5': 'Sim, por mensagem no celular',
  'Q6': 'Acessar certificados ou comprovantes de participação',
  'Q7': 'Importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Melhor comunicação',
  'Q10': 'Satisfeito(a)',
  'Q11': 'Psicologia',
  'Q12': 'Não trabalho',
  'Q13': 'Mais de 10 horas',
  'Q14': 'Baixa, prefiro métodos manuais',
  'Q15': ['Outros: Aumentar networking',
   'Ganhar créditos acadêmicos',
   'Conectar-se com outras pessoas']},
 {'Q1': 'Eventos culturais',
  'Q2': 'Raramente',
  'Q3': 'Redes sociais',
  'Q4': ['Recomendações personalizadas',
   'Avaliações e feedbacks das atividades',
   'Calendário integrado de eventos'],
  'Q5': 'Não gostaria de receber notificações',
  'Q6': 'Encontrar atividades relevantes',
  'Q7': 'Pouco importante',
  'Q8': 'Não, mas gostaria de usar',
  'Q9': 'Mais opções de atividades',
  'Q10': 'Insatisfeito(a)',
  'Q11': 'Engenharia Civil',
  'Q12': 'Sim, trabalho parcial',
  'Q13': 'Entre 5 e 10 horas',
  'Q14': 'Moderada, utilizo quando necessário',
  'Q15': ['Relaxar e fazer algo divertido', 'Explorar novos interesses']},
 {'Q1': 'Eventos esportivos',
  'Q2': 'Algumas vezes por semestre',
  'Q3': 'Redes sociais',
  'Q4': ['Avaliações e feedbacks das atividades',
   'Exploração de atividades por categoria',
   'Rede de contatos entre participantes'],
  'Q5': 'Não gostaria de receber notificações',
  'Q6': 'Processo de inscrição',
  'Q7': 'Importante',
  'Q8': 'Não vejo utilidade',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Muito satisfeito(a)',
  'Q11': 'Arquitetura',
  'Q12': 'Não trabalho',
  'Q13': 'Entre 5 e 10 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Relaxar e fazer algo divertido', 'Conectar-se com outras pessoas']},
 {'Q1': 'Grupos de estudo',
  'Q2': 'Nunca',
  'Q3': 'Comunicados internos',
  'Q4': ['Recomendações personalizadas',
   'Rede de contatos entre participantes',
   'Calendário integrado de eventos'],
  'Q5': 'Sim, por mensagem no celular',
  'Q6': 'Acompanhar as datas dos eventos',
  'Q7': 'Moderadamente importante',
  'Q8': 'Não, mas gostaria de usar',
  'Q9': 'Facilidade de inscrição',
  'Q10': 'Insatisfeito(a)',
  'Q11': 'Ciências da Computação',
  'Q12': 'Não trabalho',
  'Q13': 'Mais de 10 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Outros: Aumentar networking', 'Conectar-se com outras pessoas']},
 {'Q1': 'Outros: Voluntariado',
  'Q2': 'Algumas vezes por semestre',
  'Q3': 'Recomendação de colegas',
  'Q4': ['Recomendações personalizadas',
   'Exploração de atividades por categoria',
   'Histórico de participação',
   'Calendário integrado de eventos',
   'Rede de contatos entre participantes'],
  'Q5': 'Sim, por ambos (e-mail e mensagem)',
  'Q6': 'Acompanhar as datas dos eventos',
  'Q7': 'Não importante',
  'Q8': 'Não, mas gostaria de usar',
  'Q9': 'Mais opções de atividades',
  'Q10': 'Neutro(a)',
  'Q11': 'Educação Física',
  'Q12': 'Sim, estou em estágio',
  'Q13': 'Mais de 10 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Outros: Aumentar networking',
   'Explorar novos interesses',
   'Relaxar e fazer algo divertido']},
 {'Q1': 'Outros: Voluntariado',
  'Q2': 'Nunca',
  'Q3': 'Outros: Site institucional',
  'Q4': ['Inscrição online',
   'Histórico de participação',
   'Recomendações personalizadas',
   'Exploração de atividades por categoria',
   'Calendário integrado de eventos'],
  'Q5': 'Sim, por mensagem no celular',
  'Q6': 'Acessar certificados ou comprovantes de participação',
  'Q7': 'Moderadamente importante',
  'Q8': 'Não vejo utilidade',
  'Q9': 'Melhor comunicação',
  'Q10': 'Insatisfeito(a)',
  'Q11': 'Letras Português',
  'Q12': 'Sim, trabalho parcial',
  'Q13': 'Entre 2 e 5 horas',
  'Q14': 'Moderada, utilizo quando necessário',
  'Q15': ['Outros: Aumentar networking',
   'Ganhar créditos acadêmicos',
   'Explorar novos interesses']},
 {'Q1': 'Outros: Voluntariado',
  'Q2': 'Nunca',
  'Q3': 'Comunicados internos',
  'Q4': ['Calendário integrado de eventos',
   'Rede de contatos entre participantes',
   'Recomendações personalizadas'],
  'Q5': 'Sim, por e-mail',
  'Q6': 'Processo de inscrição',
  'Q7': 'Importante',
  'Q8': 'Não, mas gostaria de usar',
  'Q9': 'Melhor comunicação',
  'Q10': 'Insatisfeito(a)',
  'Q11': 'Geografia',
  'Q12': 'Sim, estou em estágio',
  'Q13': 'Menos de 2 horas',
  'Q14': 'Muito alta, utilizo frequentemente',
  'Q15': ['Melhorar habilidades profissionais', 'Ganhar créditos acadêmicos']},
 {'Q1': 'Workshops',
  'Q2': 'Nunca',
  'Q3': 'E-mails da instituição',
  'Q4': ['Rede de contatos entre participantes',
   'Exploração de atividades por categoria',
   'Inscrição online'],
  'Q5': 'Não gostaria de receber notificações',
  'Q6': 'Acessar certificados ou comprovantes de participação',
  'Q7': 'Não importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Facilidade de inscrição',
  'Q10': 'Muito insatisfeito(a)',
  'Q11': 'Sistemas de Informação',
  'Q12': 'Sim, trabalho parcial',
  'Q13': 'Mais de 10 horas',
  'Q14': 'Moderada, utilizo quando necessário',
  'Q15': ['Explorar novos interesses',
   'Outros: Aumentar networking',
   'Ganhar créditos acadêmicos']},
 {'Q1': 'Workshops',
  'Q2': 'Raramente',
  'Q3': 'Redes sociais',
  'Q4': ['Recomendações personalizadas',
   'Rede de contatos entre participantes',
   'Calendário integrado de eventos',
   'Notificações sobre mudanças nos eventos'],
  'Q5': 'Sim, por ambos (e-mail e mensagem)',
  'Q6': 'Outros: Dificuldade de conciliar horários',
  'Q7': 'Moderadamente importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Mais opções de atividades',
  'Q10': 'Muito insatisfeito(a)',
  'Q11': 'Educação Física',
  'Q12': 'Sim, trabalho parcial',
  'Q13': 'Entre 2 e 5 horas',
  'Q14': 'Moderada, utilizo quando necessário',
  'Q15': ['Conectar-se com outras pessoas', 'Explorar novos interesses']},
 {'Q1': 'Grupos de estudo',
  'Q2': 'Nunca',
  'Q3': 'Outros: Site institucional',
  'Q4': ['Rede de contatos entre participantes',
   'Avaliações e feedbacks das atividades',
   'Recomendações personalizadas',
   'Notificações sobre mudanças nos eventos'],
  'Q5': 'Sim, por e-mail',
  'Q6': 'Acompanhar as datas dos eventos',
  'Q7': 'Não importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Melhor comunicação',
  'Q10': 'Muito insatisfeito(a)',
  'Q11': 'Odontologia',
  'Q12': 'Sim, trabalho integral',
  'Q13': 'Entre 2 e 5 horas',
  'Q14': 'Baixa, prefiro métodos manuais',
  'Q15': ['Melhorar habilidades profissionais',
   'Conectar-se com outras pessoas']},
 {'Q1': 'Eventos culturais',
  'Q2': 'Nunca',
  'Q3': 'E-mails da instituição',
  'Q4': ['Histórico de participação',
   'Calendário integrado de eventos',
   'Inscrição online',
   'Notificações sobre mudanças nos eventos',
   'Recomendações personalizadas'],
  'Q5': 'Não gostaria de receber notificações',
  'Q6': 'Outros: Dificuldade de conciliar horários',
  'Q7': 'Pouco importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Insatisfeito(a)',
  'Q11': 'Ciências da Computação',
  'Q12': 'Sim, estou em estágio',
  'Q13': 'Entre 2 e 5 horas',
  'Q14': 'Baixa, prefiro métodos manuais',
  'Q15': ['Ganhar créditos acadêmicos',
   'Conectar-se com outras pessoas',
   'Relaxar e fazer algo divertido']},
 {'Q1': 'Grupos de estudo',
  'Q2': 'Raramente',
  'Q3': 'E-mails da instituição',
  'Q4': ['Inscrição online',
   'Histórico de participação',
   'Calendário integrado de eventos',
   'Exploração de atividades por categoria',
   'Avaliações e feedbacks das atividades'],
  'Q5': 'Sim, por mensagem no celular',
  'Q6': 'Outros: Dificuldade de conciliar horários',
  'Q7': 'Extremamente importante',
  'Q8': 'Não, mas gostaria de usar',
  'Q9': 'Facilidade de inscrição',
  'Q10': 'Muito satisfeito(a)',
  'Q11': 'Administração',
  'Q12': 'Não, mas procuro trabalho',
  'Q13': 'Mais de 10 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Conectar-se com outras pessoas',
   'Outros: Aumentar networking',
   'Relaxar e fazer algo divertido']},
 {'Q1': 'Eventos esportivos',
  'Q2': 'Nunca',
  'Q3': 'Comunicados internos',
  'Q4': ['Histórico de participação',
   'Inscrição online',
   'Notificações sobre mudanças nos eventos',
   'Avaliações e feedbacks das atividades',
   'Rede de contatos entre participantes'],
  'Q5': 'Não gostaria de receber notificações',
  'Q6': 'Outros: Dificuldade de conciliar horários',
  'Q7': 'Pouco importante',
  'Q8': 'Sim, frequentemente',
  'Q9': 'Melhor comunicação',
  'Q10': 'Neutro(a)',
  'Q11': 'Direito',
  'Q12': 'Sim, trabalho integral',
  'Q13': 'Entre 2 e 5 horas',
  'Q14': 'Moderada, utilizo quando necessário',
  'Q15': ['Relaxar e fazer algo divertido',
   'Ganhar créditos acadêmicos',
   'Outros: Aumentar networking']},
 {'Q1': 'Outros: Voluntariado',
  'Q2': 'Raramente',
  'Q3': 'Comunicados internos',
  'Q4': ['Calendário integrado de eventos',
   'Rede de contatos entre participantes',
   'Exploração de atividades por categoria',
   'Recomendações personalizadas'],
  'Q5': 'Sim, por e-mail',
  'Q6': 'Outros: Dificuldade de conciliar horários',
  'Q7': 'Extremamente importante',
  'Q8': 'Não vejo utilidade',
  'Q9': 'Mais acessibilidade',
  'Q10': 'Muito satisfeito(a)',
  'Q11': 'Letras - Espanhol',
  'Q12': 'Não trabalho',
  'Q13': 'Menos de 2 horas',
  'Q14': 'Nenhuma, nunca utilizei',
  'Q15': ['Conectar-se com outras pessoas',
   'Melhorar habilidades profissionais']},
 {'Q1': 'Outros: Voluntariado',
  'Q2': 'Algumas vezes por semestre',
  'Q3': 'Outros: Site institucional',
  'Q4': ['Notificações sobre mudanças nos eventos',
   'Inscrição online',
   'Exploração de atividades por categoria'],
  'Q5': 'Sim, por ambos (e-mail e mensagem)',
  'Q6': 'Processo de inscrição',
  'Q7': 'Extremamente importante',
  'Q8': 'Não vejo utilidade',
  'Q9': 'Integração com calendário pessoal',
  'Q10': 'Satisfeito(a)',
  'Q11': 'Direito',
  'Q12': 'Não trabalho',
  'Q13': 'Menos de 2 horas',
  'Q14': 'Muito alta, utilizo frequentemente',
  'Q15': ['Relaxar e fazer algo divertido',
   'Melhorar habilidades profissionais',
   'Outros: Aumentar networking']}]